services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GalDigitalGmbh\PimcoreQrcodeBundle\Controller\:
    resource: '../../Controller'
    tags: [controller.service_arguments]
    public: true

  GalDigitalGmbh\PimcoreQrcodeBundle\EventListener\AdminListener:
    tags:
      - { name: kernel.event_listener, event: pimcore.admin.indexAction.settings, method: addIndexSettings }
