services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GalDigitalGmbh\QrCodeBundle\Controller\:
    resource: '../../Controller'
    tags: [controller.service_arguments]
    public: true
